-- MGM fresh installs omit the legacy user_directory view. No intervening
-- migration depends on it; 00046 installs the supported user-listing RPC.
-- If an earlier migration begins referencing the view, revisit this omission.
